### ISSUE TITLE
on/off

### ISSUE THREAD

**Issue by slipmann** [F-Light/PUBG-Logitech-Mouse#10]
Sir, it is a great script. Can I make the switch differently? Like liantian script. Like this: mouse 7  - ump ON. Just on, not switching. And off any weapon by close_key only? Thank you.

**Comment by Just3rr** [comment]
yes.
delete this for every Weapon:
			macro = false
			OutputLogMessage("akm off\n")
                        OutputLCDMessage("akm off",500000)

and mouse 6 is all guns off : 

                        --all gun off：
                         close_key = 6

**Comment by slipmann** [comment]
Dont work for me. Still switching :( on/off weapons.
