### ISSUE TITLE
hi @F-Light F-Light  

### ISSUE THREAD

**Issue by hulkf16** [F-Light/PUBG-Logitech-Mouse#12]
i would thanks to your work firstly
i have made changes to your script to work well in G13 keypad  and g502 mouse
i have modified some functions to prevent script from working for some keys 
for example 
when i press key TAB 
when i change betwean auto weapon and sniper it while stop when i choose sniper
primary wheapon key for me is G5 and secondary wheapon is G3
when i choose grenade it while stop 
and when i return to my auto wheapon it while return to work 
i alsow add some functions to the script
1- when i change weapon so the color while change in g13 LCD 
if the weapon is M4  and macro is active then the color of LCD become Grean if macro disabled the color becomes red 
and when swiching to sniper or whatever single fire weapon it while change the color to Red
2-no need to activate M4 or whatever weapon again if you switch betwean weapons allready activated
3-the script now works with ADS Hold not Toggle

--------------------
if you wish to have the modified script you can send me message and i while send it to you
i am not LUA programer i am PHP programer but i know what i m doing in LUA
and sorry for my bad english
i am from irak and i live in belgium
peace

**Comment by pakoS90** [comment]
hI HULK  CAN YOU SHARE YOUR lua file? my is so bad..and doesnt work  with qbz

**Comment by F-Light** [comment]
很抱歉，现在暂时没有时间，我需要再中国的传统节日中秋节，才可能的会去优化它。

**Comment by pakoS90** [comment]
安静，有很多时间..我会等你从党回来..不要吃太多的月饼..很快见到你兄弟

**Comment by hulkf16** [comment]
祝你成功

**Comment by hulkf16** [comment]
i while share it when i finnish it
 this is vss recoil pattern need some fix
`{6,6,6,6,6,6,15,15,15,15,15,17,17,17,17,20,20,20,20,20,20} --vss`

**Comment by pakoS90** [comment]
i need expecially akm..qbz and ump

**Comment by F-Light** [comment]
ok，没问题，我会在假期补充。
它将会有一个总的系数，如果过大可以修改。这样子大多数枪都可以使用同一个数据，但这需要你去适应。
我的英语不是很好，有时候需要借助google翻译。但是我在尝试去学习，你们的英语回复我可以理解意思，最好不要翻译成中文回复我，这样我不就少了一个学习英语的机会了不是吗？
晚安，现在是北京时间00:16。

**Comment by pakoS90** [comment]
China N. 1 😎

**Comment by hulkf16** [comment]
F-Light   ok
thank you

**Comment by blake567** [comment]
some on have the recoil table for a Berly M762, QBU , VSS, SKS ?

**Comment by pakoS90** [comment]
no bro i am waiting developer update or hulkf16 .lua..at moment i am in the shit

**Comment by hulkf16** [comment]
here is the code you can test it 
[Flight Lua G502 Modified .txt](https://github.com/F-Light/PUBG-Logitech-Mouse/files/2357840/Flight.Lua.G502.Modified.txt)



But Remind i Hold to ADS not toggle
