### ISSUE TITLE
问一个很蠢的问题

### ISSUE THREAD

**Issue by Tom9998** [F-Light/PUBG-Logitech-Mouse#14]
你更新的test.lua怎么用啊，还是直接复制粘贴all.lua用就可以了😿

**Comment by fengmandaren** [comment]
就是枪械的测试数据，直接改正式宏的枪数据，复制粘贴改了就可以了。但是这种东西还是得自己慢慢调，这个月要出训练场了，可以慢慢调枪了

**Comment by F-Light** [comment]
这个问题不算得愚蠢，但是你可以比较，要是我想测试枪械，就要落地成盒，所以比较懒。
