### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by blake567** [F-Light/PUBG-Logitech-Mouse#2]
how it works in the game, which buttons activate the look x2, x4 red dot

**Comment by F-Light** [comment]
such as  g1 g2 g3 ....g9 ,If you have Logitech G502.
You may choose such as you prefer。
![image](https://www.lbysg.top/20180328233909.jpg)
 @blake567

**Comment by blake567** [comment]
ya i have that Mouse. but which buttons activate the no reciol in x4 scope

**Comment by F-Light** [comment]
activate：  Caps Lock 
@blake567

**Comment by blake567** [comment]
ty
