### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ruhey79** [F-Light/PUBG-Logitech-Mouse#3]
![20180329_051630](https://user-images.githubusercontent.com/15170867/38053919-5ab95622-3310-11e8-8d73-4b0bbdc61ad2.png)

**Comment by F-Light** [comment]
Ctrl+A→Delete →openfile All.lua→Ctrl+A→Ctrl+c→Ctrl+v
😃

**Comment by ruhey79** [comment]
thx bro.
