### ISSUE TITLE
Single shot vs auto/burst ?

### ISSUE THREAD

**Issue by jinny7899** [F-Light/PUBG-Logitech-Mouse#4]
what is better ?

**Comment by blake567** [comment]
i use all in single. but need better recoil table for x4 scope

**Comment by F-Light** [comment]
I recommend using single shot.
in the x4 scope,I think it is good to use m16 and m4.

**Comment by jinny7899** [comment]
i feel like it abit slower if i use single shot on normal m4 reddot something like that
