### ISSUE TITLE
The Recoil are not Great?!?

### ISSUE THREAD

**Issue by giaphongdau** [F-Light/PUBG-Logitech-Mouse#7]
I didn't mean anything but the recoil seem didn't that great, when I active m4, the recoil going down, is there anything I can do about it? I will help you out with testing and stuff, to make the recoil more perfect.

**Comment by blake567** [comment]
help so i dont open a issue again.How do I work with the ADS shooting mode? If I keep pressing the right button the recoil is the same always until when I activate the x4 scope.
