### ISSUE TITLE
we need game settings 

### ISSUE THREAD

**Issue by burnedredline** [F-Light/PUBG-Logitech-Mouse#8]
I think 
aim/ads null
aim null
ads = right mouse click 

right ? 

We need English Translation

1.进设置界面，控制界面 aim/ads 设置为空 aim 设置为空 ads 设置为右键

aim的意思是肩射，以前按住右键不松就是肩射，如果喜欢肩射的可以另设置一个按键，否则肩射和镜射都用右键的话右键不松还是肩射

2.设置界面，游戏内容界面 瞄准视角，切换改成保持

ok了，有镜的话按住右键就是开镜，然后松开就自动关镜了。无镜的话就是按住不松机瞄。

**Comment by burnedredline** [comment]
And Gameplay settings 

HoldBreath = toggle
ads = ?

**Comment by F-Light** [comment]
还原默认就好，什么设置都不用改。
当然，5.3的大更新我依旧没有时间去测试，或者说更新枪械数据

**Comment by Just3rr** [comment]
any options that i can spray with m16 and 4x full auto ? if i press "capslock" they only shot singlefire


任何选项，我可以用m16和4x全自动喷雾？如果我按“大写锁定”，他们只能拍摄单枪

**Comment by jinny7899** [comment]
you guys use 0.70 or 1.0 ?

**Comment by burnedredline** [comment]
i use 1.0 Check fork.
