### ISSUE TITLE
spray

### ISSUE THREAD

**Issue by Just3rr** [F-Light/PUBG-Logitech-Mouse#9]
i set all weapons to singleshot.

if i press capslock for 4x i can't spray full auto. i forgott something?

**Comment by burnedredline** [comment]
Right click open scope 
press caps lock button - This is 1 shot 4x
full auto spray hold "ctrl" button :D 
But This is now outdated wait a update !

**Comment by Just3rr** [comment]
new coeffizient is 1.56. he updated allrdy.

**Comment by F-Light** [comment]
有时间我会去解决的。
